import React, { Component } from 'react';

export default class Recipes extends Component {
  //state...
  //proptypes....
  //componentdidmount...
  //query...find recipes...
  //fetch recipes...
  //componentsdidupdate...
  //nextpage, prevpage...

  render() {
    return (
      <p>Here are some good shit recipes</p>
    );
  }
}
